### ISSUE TITLE
Use of URLMismatchError(?)

### ISSUE THREAD

**Issue by bathos** [ivansandrk/multi-apps#6]
URLMismatchError is [being marked as deprecated](https://github.com/whatwg/webidl/pull/1202). It seems the behind-a-flag [implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/subapps/sub_apps.cc;l=154;drc=ce8004874365e079abf1fe15edbdb5c15e2e6e92) of this proposal (I think — not 100% sure I landed in the right place) is using it. This error code isn’t used by anything else. I don’t know if there’s spec text to go with `subApps` yet, but heads-up that you may want to swap in a different error code if/when there is.

![navigator.subApps.add rejecting with URLMismatchError](https://user-images.githubusercontent.com/6257356/192655718-be5e2b27-64ba-4fc4-852b-ceb14d7df2be.png)

**Comment by ivansandrk** [comment]
Thanks for the heads-up, that's useful! Will make sure to swap in a different error code.

(and you're correct - no spec yet)

**Comment by ivansandrk** [comment]
This is fixed now, thanks!

https://bugs.chromium.org/p/chromium/issues/detail?id=1393343
